# Generated by Django 4.1.4 on 2023-01-02 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(max_length=1000)),
                ('document', models.FileField(upload_to='research')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ongoing', 'ongoing'), ('presented', 'presented'), ('published', 'published')], max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
