# Generated by Django 4.1.4 on 2023-01-04 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('researches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_publisher', to=settings.AUTH_USER_MODEL),
        ),
    ]
