# Generated by Django 4.1.4 on 2022-12-30 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_actor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(upload_to='profile_picture')),
                ('address', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('contact', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='resident',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_official',
            new_name='is_coordinators',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_resident',
            new_name='is_faculty',
        ),
        migrations.AddField(
            model_name='user',
            name='is_heads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Official',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
    ]
