# Generated by Django 4.1.4 on 2023-01-06 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjects_course_code'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_actor', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_picture', models.ImageField(upload_to='profile_picture')),
                ('address', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('contact', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('subjects', models.ManyToManyField(blank=True, null=True, related_name='faculty_subjects', to='subjects.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resident',
            name='user',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_official',
            new_name='is_ext_coordinators',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_resident',
            new_name='is_faculty',
        ),
        migrations.AddField(
            model_name='user',
            name='is_heads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_res_coordinators',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Official',
        ),
        migrations.DeleteModel(
            name='Resident',
        ),
        migrations.AddField(
            model_name='departments',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departments',
            name='headed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_headed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
