# Generated by Django 4.1.4 on 2023-01-21 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_actor_departments_remove_resident_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departments',
            name='headed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_headed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
