# Generated by Django 4.1.4 on 2023-01-02 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('authentication', '0002_actor_remove_resident_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('actor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.actor')),
                ('subjects', models.ManyToManyField(null=True, related_name='faculty_subjects', to='subjects.subjects')),
            ],
            bases=('authentication.actor',),
        ),
    ]
