# Generated by Django 4.1.4 on 2023-01-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjects_course_code'),
        ('authentication', '0003_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='subjects',
            field=models.ManyToManyField(related_name='faculty_subjects', to='subjects.subjects'),
        ),
    ]
