# Generated by Django 4.1.4 on 2023-01-03 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_departments'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='departments',
            name='headed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_headed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
