# Generated by Django 4.1.4 on 2023-01-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_departments_created_by_alter_departments_headed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_coordinators',
            new_name='is_ext_coordinators',
        ),
        migrations.AddField(
            model_name='user',
            name='is_res_coordinators',
            field=models.BooleanField(default=False),
        ),
    ]
